-- updates for SEVERE_ELEMENT
UPDATE `SEVERE_ELEMENT` SET `CODE` = 'A_JPEG2K_EARLY_BOX_END', `TYPE` = 'ANOMALY', `SEVERITY` = 'BIT', `REPORT` = 'TRUE', `DESCRIPTION` = 'End of box reached before specified box length reached' WHERE `CODE` = 'A_JPEG2K_EARLY_BOX_END';
UPDATE `SEVERE_ELEMENT` SET `CODE` = 'A_JPEG2K_UNK_BOXTYPE', `TYPE` = 'ANOMALY', `SEVERITY` = 'NOTE', `REPORT` = 'FALSE', `DESCRIPTION` = 'Unrecognized (unknown) box type' WHERE `CODE` = 'A_JPEG2K_UNK_BOXTYPE';
UPDATE `SEVERE_ELEMENT` SET `CODE` = 'A_JPEG2K_UNK_MIN_VERSION', `TYPE` = 'ANOMALY', `SEVERITY` = 'NOTE', `REPORT` = 'FALSE', `DESCRIPTION` = 'Unrecognized (unknown) File Type box, MinV field value' WHERE `CODE` = 'A_JPEG2K_UNK_MIN_VERSION';
UPDATE `SEVERE_ELEMENT` SET `CODE` = 'A_JPEG2K_UNK_TBOX', `TYPE` = 'ANOMALY', `SEVERITY` = 'NOTE', `REPORT` = 'FALSE', `DESCRIPTION` = 'Unrecognized (unknown) box type value' WHERE `CODE` = 'A_JPEG2K_UNK_TBOX';
UPDATE `SEVERE_ELEMENT` SET `CODE` = 'A_JPEG2K_UNK_UNKC', `TYPE` = 'ANOMALY', `SEVERITY` = 'NOTE', `REPORT` = 'FALSE', `DESCRIPTION` = 'Unrecognized (unknown) Image Header box, UnkC field value' WHERE `CODE` = 'A_JPEG2K_UNK_UNKC';

