SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

DROP TABLE BILLING;
DROP TABLE PROGRAM;
DROP TABLE STORAGE_PREP;
DROP TABLE STORAGE_DESC_PREP;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
