INSERT into FORMAT 
set CODE = 'APP_PDF_1_7', MEDIA_TYPE = 'application/pdf', MEDIA_TYPE_VERSION = '1.7', SUPPORT_LEVEL = 'FULLY_SUPPORTED', ACTION_PLAN = 1;
UPDATE DATABASE_VERSION SET MIGRATION_NUMBER=36;