-- widen the links
ALTER TABLE `DISTRIBUTED` MODIFY `LINKS` mediumtext NOT NULL;
ALTER TABLE `DISTRIBUTED` MODIFY `BROKEN_LINKS` mediumtext NOT NULL;
ALTER TABLE `DISTRIBUTED` MODIFY `IGNORED_LINKS` mediumtext NOT NULL;
