-- inserts for COMPRESSION
INSERT INTO `COMPRESSION` (`CODE`, `DESCRIPTION`) VALUES ('AVC1','Advance Video Coding (H.264)');
INSERT INTO `COMPRESSION` (`CODE`, `DESCRIPTION`) VALUES ('JPEG_LS','JPEG-LS, See JPEG2000 JPX 15444-2.');
INSERT INTO `COMPRESSION` (`CODE`, `DESCRIPTION`) VALUES ('SMC','Graphics');

