-- Add MEDIA_TYPE and FORMAT code for PRO files
INSERT INTO MEDIA_TYPE VALUES('text/x-pro','PRO files generated by PrimeOCR');
INSERT INTO FORMAT VALUES ('TXT_PRO','text/x-pro','','','FULLY_SUPPORTED',1);
