SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

update MEDIA_TYPE SET TYPE = 'audio/x-wav' where TYPE = 'audio/x-wave';
update`FORMAT` SET MEDIA_TYPE = 'audio/x-wav' WHERE CODE = 'AUDIO_WAVE';
update ARCHIVE_LOGIC SET MEDIA_TYPE = 'audio/x-wav' WHERE MEDIA_TYPE = 'audio/x-wave';

UPDATE DATABASE_VERSION SET MIGRATION_NUMBER=25;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

